\hypertarget{class_x_m_l_constructor_exception}{}\section{X\+M\+L\+Constructor\+Exception Class Reference}
\label{class_x_m_l_constructor_exception}\index{X\+M\+L\+Constructor\+Exception@{X\+M\+L\+Constructor\+Exception}}


{\ttfamily \#include $<$X\+M\+L\+Constructor\+Exception.\+h$>$}



\subsection{Detailed Description}
\{core\} Exceptions thrown by some lib\+S\+B\+ML constructors.



In some situations, constructors for S\+B\+ML objects may need to indicate to callers that the creation of the object failed. The failure may be for different reasons, such as an attempt to use invalid parameters or a system condition such as a memory error. To communicate this to callers, those classes will throw an \hyperlink{class_x_m_l_constructor_exception}{X\+M\+L\+Constructor\+Exception}. 

In languages that don\textquotesingle{}t have an exception mechanism (e.\+g., C), the constructors generally try to return an error code instead of throwing an exception.

\begin{DoxySeeAlso}{See also}
\hyperlink{class_s_b_m_l_constructor_exception}{S\+B\+M\+L\+Constructor\+Exception} 
\end{DoxySeeAlso}


The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
\hyperlink{_x_m_l_constructor_exception_8h}{X\+M\+L\+Constructor\+Exception.\+h}\end{DoxyCompactItemize}
